Ltitle: Aindriya Barua – Buy me a biryani!
logo:  # you can add own logo.
description:  hjhjhjh
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://buymeabiryani.github.io/" # the base hostname & protocol for your site, e.g. http://example.com


# Author Settings
author:
  name: Hues On My Canvas
  image: '/assets/img/HuesLogo (1).png'
  job: Aindriya Barua | Artist | Poetess
  bio: Hey there!  This is a crowdfunding effort where I am trying to accumulate money to buy myself a ukulele and a wakom tablet. You can help me in reaching my goal by sending as less as Rs. 100 or $2.
  email: barua.aindriya@gmail.com


# Contact links
contact:
  - name: Twitter
    link: https://twitter.com/
  - name: Facebook
    link: https://facebook.com/
  - name: Instagram
    link: https://instagram.com/hues.on.my.canvas


# Comment Section (Disqus)
disqus-identifier: mr-brown # add your shortname for Disqus Comment. For example mr-brown


# Google Analytics
google-analytics: # add your identifier. For example UA-99631805-1.


# Build settings
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-sitemap
  - jekyll/tagging

# Pages Path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext

include:
  - _pages

# Tags
tag_page_dir:         tag
tag_page_layout:      tag-page
tag_permalink_style:  pretty

sass:
  sass_dir: _sass
  style: compressed


# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
